<?php
/**
 * Макет страницы - шаг "Регистрация веб-приложения".
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Веб-студия
 * @package gm.setup
 * @since 1.0
 * 
 * @var string $licenseKey
 * @var \Gm\Installer\InstallerConfig $state
 * @var \Gm\Setup\Setup $installer
 * @var \Gm\Setup\NewChoice\StepLicense $step
 * @var string $assets
 * @var callable $t
 */

$licenseApply = ($state->licenseApply ?? false) ? 'checked' : '';
?>

<h1><?= $t('License agreement') ?></h1>

<div style="text-align: justify;"><?php $step->showLicense() ?></div>
<br>
<form class="form" class="form form-horizontal" action="" method="POST">
    <input type="hidden" id="form-action" name="action" value="" />

    <div class="form-wrap">
        <div class="row">
            <div class="form-check col-sm-8">
                <input class="form-check-input" type="checkbox" id="licenseApply" name="licenseApply" <?= $licenseApply ?> />
                <label class="form-check-label" for="licenseApply"><?= $t('I have read and accept the license agreement') ?></label>
            </div>
        </div>
    </div>

    <?= $step->showMessages() ?>

    <div class="form__navbar">
        <a class="btn btn-light btn-prev btn-lg" href="<?= $installer->makeUrl('choice') ?>"><?= $t('Back') ?></a>
        <button type="submit" class="btn btn-default btn-next btn-lg" data-action="license"><?= $t('Next') ?></button>
    </div>
</form>
