<?php
/**
 * Макет страницы - шаг "Предварительная проверка".
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Веб-студия
 * @package gm.setup
 * @since 1.0
 * 
 * @var \Gm\Setup\SetupStep $step
 * @var string $assets
 * @var callable $t
 */

?>
<form class="form form-horizontal" action="#navbar" method="POST">
    <input type="hidden" id="form-action" name="action" value="" />
    <div class="form__title"><?= $t('Preliminary check') ?></div>
    <p><?= $t('Your web application must meet the required parameters') ?>. <?= $t('If one of the parameters is highlighted in red, then you need to fix it') ?>.</p>
    <p><?= $t('If you continue with the installation without patching, your web application may be broken') ?>.</p>

    <p>&nbsp;</p>
<?php if ($checked) : ?>
    <table class="table table-check">
        <thead>
            <tr>
                <th scope="col"><?= $t('Parameter') ?></th>
                <th scope="col"><?= $t('Required') ?></th>
                <th scope="col"><?= $t('Current') ?></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><?= $t('Web server version') ?> <b>Apache</b></td>
                <td><?= REQUIRED_APACHE_VERSION ?> <?= $t('and higher') ?></td>
                <td><?= $checked['apache'] ?></td>
            </tr>
            <tr>
                <td><?= $t('Version') ?> <b>PHP</b></td>
                <td><?= REQUIRED_PHP_VERSION ?> <?= $t('and higher') ?></td>
                <td><?= $checked['php'] ?></td>
            </tr>
            <tr>
                <td colspan="3"><b><?= $t('PHP directives') ?>:</b></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a target="_blank" href="https://www.php.net/manual/ru/datetime.configuration.php#ini.date.timezone">date.timezone</a></div>
                    <div class="desc"><?= $t('default time zone') ?></div>
                </td>
                <td><?= $t('Installed') ?></td>
                <td><?= $checked['date.timezone'] ?></td>
            </tr>

            <tr>
                <td class="left-offset">
                    <div><a target="_blank" href="https://www.php.net/manual/ru/opcache.configuration.php#ini.opcache.enable">opcache.enable</a></div>
                    <div class="desc"><?= $t('enable opcode caching') ?></div>
                </td>
                <td>1</td>
                <td><?= $checked['opcache.enable'] ?></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a target="_blank" href="https://www.php.net/manual/ru/filesystem.configuration.php#ini.allow_url_fopen">allow_url_fopen</a></div>
                    <div class="desc"><?= $t('includes support for URL wrappers') ?></div>
                </td>
                <td>1</td>
                <td><?= $checked['allow_url_fopen'] ?></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a target="_blank" href="https://www.php.net/manual/ru/filesystem.configuration.php#ini.allow_url_include">allow_url_include</a></div>
                    <div class="desc"><?= $t('support for working with URL a number of functions') ?></div>
                </td>
                <td>0</td>
                <td><?= $checked['allow_url_include'] ?></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a target="_blank" href="https://www.php.net/manual/ru/ini.core.php#ini.default_charset">default_charset</a></div>
                    <div class="desc"><?= $t('default encoding for functions') ?></div>
                </td>
                <td><?= $t('Installed') ?></td>
                <td><?= $checked['default_charset'] ?></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a target="_blank" href="https://www.php.net/manual/ru/ini.core.php#ini.post-max-size">post_max_size</a></div>
                    <div class="desc"><?= $t('the maximum allowable size of data sent by the POST method') ?></div>
                </td>
                <td><?= $t('Installed') ?></td>
                <td><?= $checked['post_max_size'] ?></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a target="_blank" href="https://www.php.net/manual/ru/ini.core.php#ini.upload-max-filesize">max_file_uploads</a></div>
                    <div class="desc"><?= $t('maximum uploaded size') ?></div>
                </td>
                <td><?= $t('Installed') ?></td>
                <td><?= $checked['max_file_uploads'] ?></td>
            </tr>

            <tr>
                <td class="left-offset">
                    <div><a target="_blank" href="https://www.php.net/manual/ru/ini.core.php#ini.memory-limit">memory_limit</a></div>
                    <div class="desc"><?= $t('the maximum amount of memory a script is allowed to use') ?></div>
                </td>
                <td><?= $t('Installed') ?></td>
                <td><?= $checked['memory_limit'] ?></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a target="_blank" href="https://www.php.net/manual/ru/info.configuration.php#ini.max-execution-time">max_execution_time </a></div>
                    <div class="desc"><?= $t('maximum time in seconds for script loading') ?></div>
                </td>
                <td><?= $t('Installed') ?></td>
                <td><?= $checked['max_execution_time'] ?></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a target="_blank" href="https://www.php.net/manual/ru/ini.core.php#ini.short-open-tag">short_open_tag</a></div>
                    <div class="desc"><?= $t('is short form PHP tags allowed') ?></div>
                </td>
                <td>1</td>
                <td><?= $checked['short_open_tag'] ?></td>
            </tr>
            <tr>
                <td colspan="3"><b><?= $t('PHP Modules') ?>:</b></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a href="https://www.php.net/manual/ru/book.mysqli.php" target="_blank"><?= $t('MySQL module') ?></a> (mysqli)</div>
                    <div class="desc"><?= $t('working with MySQL database server') ?></div>
                </td>
                <td><?= $t('Loaded') ?></td>
                <td><?= $checked['mysqli'] ?></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a href="https://www.php.net/manual/ru/book.session" target="_blank"><?= $t('Session module') ?></a> (session)</div>
                    <div class="desc"><?= $t('user session management') ?></div>
                </td>
                <td><?= $t('Loaded') ?></td>
                <td><?= $checked['session'] ?></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a href="https://www.php.net/manual/ru/book.json" target="_blank"><?= $t('JSON module') ?></a> (json)</div>
                    <div class="desc"><?= $t('the module implements work with the JSON text data exchange format') ?></div>
                </td>
                <td><?= $t('Loaded') ?></td>
                <td><?= $checked['json'] ?></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a href="https://www.php.net/manual/ru/book.mbstring.php" target="_blank"><?= $t('Module Multibyte strings') ?></a> (mbstring)</div>
                    <div class="desc"><?= $t('module provides functions for working with multibyte strings') ?></div>
                </td>
                <td><?= $t('Loaded') ?></td>
                <td><?= $checked['mbstring'] ?></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a href="https://www.php.net/manual/ru/book.curl" target="_blank"><?= $t('cURL module') ?></a> (curl)</div>
                    <div class="desc"><?= $t('library of functions for working with URL') ?></div>
                </td>
                <td><?= $t('Loaded') ?></td>
                <td><?= $checked['curl'] ?></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a href="https://www.php.net/manual/ru/book.intl" target="_blank"><?= $t('Internationalization module') ?></a> (intl)</div>
                    <div class="desc"><?= $t('formatting, transliteration, encoding conversion, etc.') ?></div>
                </td>
                <td><?= $t('Loaded') ?></td>
                <td><?= $checked['intl'] ?></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a href="https://www.php.net/manual/ru/book.image" target="_blank"><?= $t('Image processing module') ?></a> (gd)</div>
                    <div class="desc"><?= $t('working with image files in various formats') ?></div>
                </td>
                <td><?= $t('Loaded') ?></td>
                <td><?= $checked['gd'] ?></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a href="https://www.php.net/manual/ru/book.zip.php" target="_blank"><?= $t('Zip compression and archiving module') ?></a> (zip)</div>
                    <div class="desc"><?= $t('allows you to read and write to ZIP archives') ?></div>
                </td>
                <td><?= $t('Loaded') ?></td>
                <td><?= $checked['zip'] ?></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a href="https://www.php.net/manual/ru/book.libxml.php" target="_blank"><?= $t('libXML module') ?></a> (libxml)</div>
                    <div class="desc"><?= $t('working with the XML file format') ?></div>
                </td>
                <td><?= $t('Loaded') ?></td>
                <td><?= $checked['libxml'] ?></td>
            </tr>
            <tr>
                <td class="left-offset">
                    <div><a href="https://developer.redis.com/develop/php/" target="_blank"><?= $t('Redis server connection module') ?></a> (redis)</div>
                    <div class="desc"><?= $t('storing data on a remote server') ?> <a href="https://redis.io/" target="_blank">Redis</a></div>
                </td>
                <td><?= $t('Loaded') ?></td>
                <td><?= $checked['redis'] ?></td>
            </tr>
        </tbody>
    </table>
<?php endif ?>

    <?= $step->showMessages() ?>

    <div id="navbar" class="form__navbar">
        <a class="btn btn-light btn-prev btn-lg" href="<?= $installer->makeUrl('welcome') ?>"><?= $t('Back') ?></a>
        <button type="submit" class="btn btn-default btn-next btn-lg" data-action="next"><?= $t('Next') ?></button>
    </div>
</form>
